# version: '3.8'

services:
  # web:
  #   build: 
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #   # command: python app.py run -h 0.0.0.0
  #   volumes:
  #     - ./services/web/:/usr/src/app/
  #   ports:
  #     - 5001:5000
  #   env_file:
  #     - ./.env.dev

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres_server
      ADMINER_DEFAULT_DB_NAME: quizz_me
    depends_on:
      - postgres_server

  postgres_server:
    image: postgres
    environment:
      POSTGRES_DB: quizz_me
      POSTGRES_USER: quizz
      POSTGRES_PASSWORD: quizz
    ports:
      - 5432:5432
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
