services:
  web:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ../.env
    environment:
      DB_HOST: postgres_server
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: src/
    depends_on:
      - postgres_server

  adminer:
    extends:
      file: docker-compose-db.yml
      service: adminer

  postgres_server:
    extends:
      file: docker-compose-db.yml
      service: postgres_server
